apiVersion: v1
kind: Pod
metadata:
  name: my-app
  namespace: test
spec:
  containers:
  - name: nginx
    image: nginx:latest
    volumeMounts:
    - name: config-data
      mountPath: /data
  initContainers:
  - name: config-data
    image: busybox
    command:
    - wget
    - "-O"
    - "/data/config"
    - http://kubernetes.io
    volumeMounts:
    - name: config-data
      mountPath: /data
  volumes:
  - name: config-data
    emptyDir: {}
