apiVersion: v1
kind: ConfigMap
metadata:
  name: test-readonly
  namespace: test
data:
  init.sh: |
    #!/bin/sh
    set -x
    #echo ${HOSTNAME} $(hostname -I | awk '{print $1}') > /data/index.html
    echo "<html><head><title>HTTP Hello World</title></head><body><h1>${HOSTNAME} $(hostname -I | awk '{print $1}')</h1></body></html>" > /data/index.html

---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: test-nginx
  namespace: test
spec:
  selector:
    matchLabels:
      app: test-nginx
  replicas: 3
  template:
    metadata:
      labels:
        app: test-nginx
    spec:
      initContainers:
      - name: text-data
        image: centos:latest
        command:
        - "/bin/sh"
        - "/test-readonly/init.sh"
        workingDir: /test-readonly
        volumeMounts:
        - name: test-readonly
          mountPath: /test-readonly
        - name: text-data
          mountPath: /data
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - name: http
          containerPort: 80
        volumeMounts:
        - name: text-data
          mountPath: /usr/share/nginx/html
      volumes:
      - name: text-data
        emptyDir: {}
      - name: test-readonly
        configMap:
          name: test-readonly
---
apiVersion: v1
kind: Service
metadata:
  name: test-nginx
  namespace: test
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: test-nginx
  type: LoadBalancer

