apiVersion: v1
kind: ConfigMap
metadata:
  name: test-readonly
  namespace: test
data:
  test-text1: |
    hoge
  test-text2: |
    huga
  test-text3: |
    piyo
  init.sh: |
    #!/bin/sh
    set -x
    echo ${HOSTNAME} > /data/hostname
    echo $(hostname -I | awk '{print $1}') > /data/ip_address
    cp * /data

---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: test-app
  namespace: test
spec:
  selector:
    matchLabels:
      app: test-app
  replicas: 3
  template:
    metadata:
      labels:
        app: test-app
    spec:
      initContainers:
      - name: text-data
        image: centos:latest
        command:
        - "/bin/sh"
        - "/test-readonly/init.sh"
        workingDir: /test-readonly
        volumeMounts:
        - name: test-readonly
          mountPath: /test-readonly
        - name: text-data
          mountPath: /data
      containers:
      - name: busybox
        image: busybox:latest
        command: ["sh", "-c", "tail -f /dev/null"]
        volumeMounts:
        - name: text-data
          mountPath: /data
      volumes:
      - name: text-data
        emptyDir: {}
      - name: test-readonly
        configMap:
          name: test-readonly
