kind: PersistentVolume
apiVersion: v1
metadata:
  name: mariadb-pv-002
  namespace: mysql
  labels:
    type: nfs
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /var/share/pv002
    server: 192.168.0.11
