apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: gogs
  namespace: mysql
  labels:
    app: gogs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gogs
  template:
    metadata:
      labels:
        app: gogs
    spec:
      containers:
        - name: gogs
          image: gogs/gogs:latest
          ports:
          - name: ssh
            containerPort: 22
          - name: http
            containerPort: 3000
          livenessProbe:
            tcpSocket:
              port: 3000
            initialDelaySeconds: 1
            timeoutSeconds: 5
          readinessProbe:
            tcpSocket:
              port: 3000
            initialDelaySeconds: 1
            timeoutSeconds: 5
