apiVersion: v1
kind: Service
metadata:
  name: gogs
  namespace: mysql
  labels:
    app: gogs
  annotations:
    'prometheus.io/scrape': 'true'
spec:
  ports:
  - name: ssh
    protocol: TCP
    port: 22
    targetPort: 22
  - name: http
    protocol: TCP
    port: 3000
    targetPort: 3000
  selector:
    app: gogs
  type: LoadBalancer
