apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mariadb
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
      - image: mariadb:5.5.61
        name: mariadb
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: rootPassword
        ports:
        - containerPort: 3306
          name: mariadb
        volumeMounts:
          - name: mariadb-mycnf
            mountPath: /etc/mysql/my.cnf
            subPath: my.cnf
          - name: mariadb-persistent-storage
            mountPath: /var/lib/mysql
      volumes:
        - name: mariadb-mycnf
          configMap:
            name: mariadb-mycnf
        - name: mariadb-persistent-storage
          persistentVolumeClaim:
            claimName: mariadb-pvc-001

---
apiVersion: v1
kind: Service
metadata:
  name: mariadb
spec:
  ports:
  - name: mysql
    port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: mariadb
  type: ClusterIP
