kind: PersistentVolume
apiVersion: v1
metadata:
  name: mariadb-pv-001
  labels:
    type: nfs
spec:
  capacity:
    storage: 30Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /var/share
    server: 192.168.0.11
